export const ActionType = {
  UPDATE_POSTS: "UPDATE_POSTS",
  UPDATE_SEARCHED_POSTS: "UPDATE_SEARCHED_POSTS",
  UPDATE_PAGES_COUNT: "UPDATE_PAGES_COUNT",
  CHANGE_APP_STATUS: "CHANGE_APP_STATUS",
} as const;
